version: '3'
services:
  bot:
    image: lacolle87/gundam_bot:latest
    container_name: gundam-bot-container
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./logs:/app/logs
    restart: always